@startuml architecture
interface "REST API" as r1
interface "HTTP" as r2
interface "Message Passing System" as ac

package "cluster" as c {
  [ChargingStationActor] as CSA
  CSA - ac
}

package "service" as S {
  [ChargingStationProvider] as CSP
  [ChargingStationService] as CSS
  CSP - CSS
  CSP --> ac
  CSS - r2
}

package "app" as A {
  [UserApp] as UA
  UA --> r1
  UA --> r2
}

package "server" as S1 {
  [AuthServer] as AS
  AS - r1
}
@enduml