name: compile
on:
  push:
    branches:
      - docs
      - main
jobs:
  compile:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    concurrency:
      group: release
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          ref: docs
          submodules: recursive

      - name: Compile latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "report.tex"
          working_directory: "docs/"
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape

      - name: copy ontology file
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          ref: main
          path: ./main-repo
          submodules: recursive

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          npm install
          npx semantic-release